version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: meu_postgres_novo
    environment:
      POSTGRES_USER: votingdb_postgres
      POSTGRES_PASSWORD: vote_123
      POSTGRES_DB: votingdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
